#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

import os
import shutil
import subprocess


source_path = os.environ['SOURCE_PATH']
add_dependencies_cmd = os.environ['ADD_DEPENDENCIES_CMD']
base_definition_path = os.environ['BASE_DEFINITION_PATH']
component_descriptor_path = os.environ['COMPONENT_DESCRIPTOR_PATH']

with open(os.path.join(source_path, 'CC_UTILS_VERSION')) as f:
    cc_utils_version = f.read().strip()

command = f'{add_dependencies_cmd} --component-dependencies \'{{"name": "github.com/gardener/cc-utils", "version": "{cc_utils_version}"}}\''
print('running cmd: ', command)
result = subprocess.run(command, env=os.environ, shell=True, capture_output=True)
if result.returncode != 0:
    raise Exception("cannot add component dependency: " + str(result))

shutil.copyfile(
    src=base_definition_path,
    dst=component_descriptor_path,
)