#!/bin/bash -e

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"

echo 'Running flake8 for all python modules..'

if flake8 --max-line-length=141 --count --format=pylint ${src_dir}; then
    echo 'flake8 succeeded'
    exit 0
else
    echo 'flake8 found errors (see above)'
    exit 1
fi

