#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

import os

source_path = os.environ['SOURCE_PATH']
component_name = os.environ['COMPONENT_NAME']
dependency_name = os.environ['DEPENDENCY_NAME']
dependency_version = os.environ['DEPENDENCY_VERSION']


if component_name == 'github.com/gardener/cnudie-transport-tool':
    if dependency_name == 'github.com/gardener/cc-utils':
        with open(os.path.join(source_path, 'CC_UTILS_VERSION'), 'w') as f:
            f.write(dependency_version)
    else:
        raise NotImplementedError(f"Don't know how to update {dependency_name}.")