#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

import os
import re

import ci.util
import gci.componentmodel as cm
import product.v2


source_path = os.environ['SOURCE_PATH']
component_name = os.environ['COMPONENT_NAME']
dependency_name = os.environ['DEPENDENCY_NAME']
dependency_version = os.environ['DEPENDENCY_VERSION']


def update_cc_utils_dependency(cc_utils_cd: cm.ComponentDescriptor):
    cc_job_image = [
        res for res in cc_utils_cd.component.resources
        if res.type is cm.ResourceType.OCI_IMAGE and res.name == 'job-image' 
    ]

    if len(cc_job_image) == 0:
        ci.util.fail('did not find job-image image')
    elif len(cc_job_image) > 1:
        ci.util.fail('found more than one job-image image')
    cc_job_image = cc_job_image[0]

    image_reference = cc_job_image.access.imageReference

    dockerfile = os.path.join(source_path, 'Dockerfile')
    with open(dockerfile, 'r+') as f:
        content = f.read()
        content = re.sub(
            pattern=r'(^FROM)[\s]+(eu.gcr.io/gardener-project/cc/job-image[^\r\n]*)',
            repl=f'\\1 {image_reference}',
            string=content,
        )
        f.seek(0)
        f.write(content)
        f.truncate()

    with open(os.path.join(source_path, 'CC_UTILS_VERSION'), 'w') as f:
        f.write(dependency_version)


if component_name == 'github.com/gardener/cnudie-transport-tool':
    if dependency_name == 'github.com/gardener/cc-utils':
        cc_utils_cd =  product.v2.download_component_descriptor_v2(
            component_name=dependency_name,
            component_version=dependency_version,
            ctx_repo_base_url=ci.util.check_env('CTX_REPO_URL'),
        )
        update_cc_utils_dependency(cc_utils_cd)