#!/bin/bash -e

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

if ! which pytest &>/dev/null; then
  echo "pytest is required (install with pip(3) install pytest)"
  exit 1
fi

src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"

if pytest "${src_dir}"; then
    echo 'unittest executions succeeded'
    exit 0
else
    echo 'errors were found whilst executing unittests (see above)'
    exit 1
fi
